### PR TITLE
New draw feature for Annotator 

### PR DESCRIPTION
**Pull request by ddjnw1yu**
Adding draw functionality for annotation service. 

Draw options: 
- `draw point`
- `draw line`: able to show relevance when drawing line connectivity.
- `draw polygon`

Mode options: 
- `Delete`
- `Edit`: able to drag feature position or add new comment

The more detail can be found [here](https://docs.google.com/document/d/18LjkHBA_5bNUYCM4MXxvSP5T5pNijZ1a3H7RW_ke7Os/edit).

### CODE REVIEW

**Comment by Tehsurfer** [comment]
I think `npm install` needs to be run again for the tests to be able to use `npm ci`

image

**Comment by Tehsurfer** [comment]
Few things:

1. Annotation tools do not always show after login. Sometimes the page needs to be refreshed after an Orcid login is completed
2. Annotation tools take ~1s to appear after selecting 'Annotation' in the selector. Without and loading icon, its hard to tell as a user that something is about to happen
3. I think a bit more padding is needed on the left in the tooltip:
image
4. The 'x' here should only show once a tag is selected, and should be on the tag not the heading
image
5. There is no way for the user to know how to finish a line or polygon. The user must figure out to click the last point by guessing. I would recommend having an info that says 'hit esc to finish drawing'
6. The 'Annotation' selector should stay visible while in the mode. Currently, as soon as you click outside, it will close even if you are still drawing
image

**Comment by ddjnw1yu** [comment]
1. I haven't met this issue yet. Will look at this if I can reproduce the issue.
2. add loading - Done
3. add space on the left - Done
4. show the close icon when a tag is selected - Done (having a minor issue will fix it soon)
5. will think about this...I will add this to the user guide for now
6. The dialog won't be visible while drawing. @Tehsurfer Are you talking about the relevance dialog for an existing line? If it is, I planned to close the dialog when click outside. This is because the line feature lost its focus. Probably I should disable the click when dialog is open. Will think a bit more.

**Comment by ddjnw1yu** [comment]
I will spend a few more times separating the annotation tool as an independent component.

**Review by alan-wu — APPROVED** [review]
Thanks, it works well.

**Pull request merged**
